# Generated by Django 5.1.6 on 2025-07-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kv_id', models.BigIntegerField(help_text='Hashed unique ID', unique=True)),
                ('name', models.CharField(max_length=255)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('fax', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('specializations', models.TextField(blank=True, null=True)),
                ('opening_hours', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Practice',
                'verbose_name_plural': 'Practices',
                'ordering': ['name'],
            },
        ),
    ]
